"""empty message

Revision ID: e8f0bc8fb85a
Revises: b3a6e1aacf4b
Create Date: 2024-07-23 17:35:35.954072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f0bc8fb85a'
down_revision = 'b3a6e1aacf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
